### ISSUE TITLE
Theme Data

### ISSUE THREAD

**Issue by Just-gomin** [imimtu/Brick-Front#19]
- [x] TextStyle
    - [x] Fonts
    - [x] FontSize
    - [x] FontWeight
- [x] Colors
- ~~ButtonTheme~~
- ~~TextButtonTheme~~

**Comment by Seungyeup** [comment]
올리신 이슈들 Projects > Brick's TaskLog 에 등록해주신다면 쌩유!

**Comment by Just-gomin** [comment]
@Seungyeup 아 깜빡하고 있었구만! 알겠어!ㅋㅋㅋ 여유 나는대로 정리해서 등록할께요~!

**Comment by Just-gomin** [comment]
https://api.flutter.dev/flutter/material/ThemeData-class.html

플러터 ThemeData 에서 플러터 위젯들의 ThemeData는 'colorScheme'과 'textScheme'을 바탕으로 결정된다고 명시.
Flutter 3.7 이후 부터 [Material3](https://m3.material.io/) 에 기반한 UI 디자인을 따라가고 있음.

현재 개발이 선행되는게 맞다는 판단하에, 색상과 폰트는 간단하게 위에서 언급한 'colorScheme'과 'textScheme' 만 설정하고 진행 예정.
각각 pub.dev에서 [material-color-utilities](https://github.com/material-foundation/material-color-utilities)와 googleFonts를 이용해 진행할 예정

**Comment by Just-gomin** [comment]
Closed By https://github.com/imimtu/Brick-Front/pull/20
